language: php

sudo: false

env:
  global:
    - COMPOSER_ROOT_VERSION=1.0.x-dev
    - CORE_RELEASE=4
    # The path of the module when installed by composer
    - MODULE_PATH=swiftype-search

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=MYSQL
    - php: 7.0
      env: DB=MYSQL
    - php: 7.1
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/installer
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit $MODULE_PATH/tests
